<?xml version="1.0" encoding="utf-8"?>
<testsuites>
    <testsuite name="pytest" errors="0" failures="1" skipped="0" tests="1" time="0.193"
               timestamp="2020-11-12T11:35:29.508260" hostname="JBOUGUERRA">
        <testcase classname="test.api.test_rest_api.TestRestAPI" name="test_upper" time="0.002">
            <failure message="AssertionError: 'FO' != 'FOO'&#10;- FO&#10;+ FOO&#10;?   +">self = &lt;test_rest_api.TestRestAPI
                testMethod=test_upper&gt;

                def test_upper(self):
                &gt; self.assertEqual('fo'.upper(), 'FOO')
                E AssertionError: 'FO' != 'FOO'
                E - FO
                E + FOO
                E ? +

                test\api\test_rest_api.py:11: AssertionError
            </failure>
        </testcase>
    </testsuite>
</testsuites>